---
- name: Query an Open API
  hosts: localhost
  connection: local

  vars:
      api_target: 'http://pokeapi.co'

  tasks:
  - name: Send an HTTP GET to API
    ansible.builtin.uri:
      method: GET
      url: "{{ api_target }}"
    register: data

  - name: Use debug to show what is inside of our variable
    ansible.builtin.debug:
      msg: "{{ data }}"

  - name: Slice the variable further to only return the JSON
    ansible.builtin.debug:
      msg: "{{ data.get('json') }}"

  - name: Display target key value pair
    ansible.builtin.debug:
      msg: "Transfer encoding value: {{ data.get('json').get('server') }}"
